# Generated by Django 5.2.4 on 2025-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchallenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='stroke',
            field=models.CharField(choices=[('freestyle', 'Freestyle'), ('backstroke', 'Backstroke'), ('breaststroke', 'Breaststroke'), ('butterfly', 'Butterfly')], default='freestyle', max_length=20),
        ),
    ]
